image: Visual Studio 2017
branches:
  only:
    - master

install:
  - set QTDIR=C:\Qt\5.10.1\mingw53_32
  - choco install -y InnoSetup
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;"C:\Program Files (x86)\Inno Setup 5"
build_script:
  - cd Desktop/Kalorimeter/VMeter
  - qmake VMeter.pro
  - mingw32-make
after_build:
  - windeployqt release/VMeter.exe
  - cmd: cp LICENSE release/LICENSE.txt"
  - iscc innosetup.iss
  - rm release/*.o
  - rm release/*.cpp

deploy:
  release: Kalorimeter-v$(appveyor_build_version)
  description: 'Kalorimeter Release'
  provider: GitHub
  auth_token:
    secure: dQVcTF6DiR2PNMN669wx9hUaz0/5gqIpE56zDXOW94KFmz2oFn9Qbd9ApmsQ6Wn9 # your encrypted token from GitHub
  artifact: C:/projects/kalorimeter
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
