image: Visual Studio 2017
branches:
  only:
    - master

install:
  - set QTDIR=C:\Qt\5.10.1\msvc2017_64
  - set PATH=%QTDIR%\bin;%PATH%;

build_script:
  - qmake Desktop/Kalorimeter/VMeter/VMeter.pro -spec win32-msvc
  - qmake_all
  - C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile.Release

deploy:
  release: Kalorimeter-v$(appveyor_build_version)
  description: 'Kalorimeter Release'
  provider: GitHub
  auth_token:
    secure: dQVcTF6DiR2PNMN669wx9hUaz0/5gqIpE56zDXOW94KFmz2oFn9Qbd9ApmsQ6Wn9 # your encrypted token from GitHub
  artifact: C:/projects/kalorimeter
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
